apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configMap.name }}
  namespace: {{ .Values.namespace }}
data:
  PORT: "{{ .Values.deployment.appPort }}"
  HOST: "0.0.0.0"
  NODE_ENV: "development"
  PGHOST: "postgres-service"
     