# SecretProviderClass
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ .Values.secretProvidorClass.name }}
  namespace: {{ .Values.namespace }}
spec:
  provider: azure
  secretObjects: 
  - secretName: {{ .Values.secretProvidorClass.secretName }}                           # name of the Kubernetes secret object
    type: {{ .Values.secretProvidorClass.type }}                                       # type of Kubernetes secret object (for example, Opaque, kubernetes.io/tls)
    data:
    - objectName: db-name
      key: PGDATABASE
    - objectName: postgres-password
      key: PGPASSWORD
    - objectName: postgres-username
      key: PGUSERNAME
    - objectName: okta-client-id
      key: OKTA_CLIENT_ID                                   
    - objectName: okta-secret
      key: OKTA_CLIENT_SECRET
    - objectName: okta-url
      key: OKTA_ORG_URL
    - objectName: cookie-pass
      key: COOKIE_ENCRYPT_PWD        
  parameters:
    usePodIdentity: "{{ .Values.secretProvidorClass.usePodIdentity }}"                   # Set to true for using aad-pod-identity to access your key vault
    keyvaultName: "{{ .Values.secretProvidorClass.keyvaultName }}"                       # Set to the name of your key vault
    useVMManagedIdentity: "{{ .Values.secretProvidorClass.useVMManagedIdentity }}"       # Set to true for using managed identity
    userAssignedIdentityID: {{ .Values.secretProvidorClass.userAssignedIdentityID }}  
    cloudName: ""                                                                      # [OPTIONAL for Azure] if not provided, the Azure environment defaults to AzurePublicCloud
    objects:  |
      array:
        - |
          objectName: db-name
          objectType: secret             # object types: secret, key, or cert
        - |
          objectName: okta-client-id
          objectType: secret
        - |
          objectName: okta-secret
          objectType: secret
        - |
          objectName: okta-url
          objectType: secret
        - |
          objectName: okta-secret
          objectType: secret
        - |
          objectName: postgres-password
          objectType: secret
        - |
          objectName: postgres-username
          objectType: secret
        - |
          objectName: cookie-pass
          objectType: secret

    tenantId: {{ .Values.secretProvidorClass.userAssignedIdentityID }}                # The tenant ID of the key vault